# Generated by Django 2.2.6 on 2019-10-15 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Package',
            new_name='package',
        ),
    ]
