# Generated by Django 2.2.6 on 2019-10-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191015_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='startingDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
