# Generated by Django 2.2.6 on 2019-10-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20191015_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='startingDate',
            field=models.DateField(),
        ),
    ]
