# Generated by Django 2.2.6 on 2019-10-15 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191015_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='startingDate',
            new_name='starting_Date',
        ),
    ]
